/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRepairsRouteImport } from './routes/api.repairs'
import { Route as ApiRepairsIdRouteImport } from './routes/api.repairs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepairsRoute = ApiRepairsRouteImport.update({
  id: '/api/repairs',
  path: '/api/repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepairsIdRoute = ApiRepairsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRepairsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/repairs': typeof ApiRepairsRouteWithChildren
  '/api/repairs/$id': typeof ApiRepairsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/repairs': typeof ApiRepairsRouteWithChildren
  '/api/repairs/$id': typeof ApiRepairsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/repairs': typeof ApiRepairsRouteWithChildren
  '/api/repairs/$id': typeof ApiRepairsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/repairs' | '/api/repairs/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/repairs' | '/api/repairs/$id'
  id: '__root__' | '/' | '/api/repairs' | '/api/repairs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRepairsRoute: typeof ApiRepairsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repairs': {
      id: '/api/repairs'
      path: '/api/repairs'
      fullPath: '/api/repairs'
      preLoaderRoute: typeof ApiRepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repairs/$id': {
      id: '/api/repairs/$id'
      path: '/$id'
      fullPath: '/api/repairs/$id'
      preLoaderRoute: typeof ApiRepairsIdRouteImport
      parentRoute: typeof ApiRepairsRoute
    }
  }
}

interface ApiRepairsRouteChildren {
  ApiRepairsIdRoute: typeof ApiRepairsIdRoute
}

const ApiRepairsRouteChildren: ApiRepairsRouteChildren = {
  ApiRepairsIdRoute: ApiRepairsIdRoute,
}

const ApiRepairsRouteWithChildren = ApiRepairsRoute._addFileChildren(
  ApiRepairsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRepairsRoute: ApiRepairsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
